title: My site
author: MEzza
email: michele.ezza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's a new base site that describe me

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
